CREATE DATABASE trackma1_trackmacros;
COMMIT;

CREATE TABLE tbl_user (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	email_address VARCHAR(50) NOT NULL,
	activation_code VARCHAR(12) NULL,
	activated TINYINT(4) NOT NULL DEFAULT 0
) ENGINE=MyISAM;
COMMIT;

CREATE TABLE tbl_weight (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	date DATE NOT NULL,
	weight DECIMAL(4,1) NOT NULL,
	units varchar(6) NOT NULL
) ENGINE=MyISAM;
COMMIT;
