CREATE DATABASE trackma1_trackmacros;
COMMIT;

CREATE TABLE tbl_user (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	email_address VARCHAR(50) NOT NULL,
	activation_code VARCHAR(12) NULL,
	activated TINYINT(4) NOT NULL DEFAULT 0
) ENGINE=MyISAM;
COMMIT;

CREATE TABLE tbl_weight (
	id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	date DATE NOT NULL,
	weight DECIMAL(4,1) NOT NULL,
	units VARCHAR(6) NOT NULL
) ENGINE=MyISAM;
COMMIT;

CREATE TABLE tbl_dailyfood (
	id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	date DATE NOT NULL,
	food_id INT(11) NOT NULL,
	amount DECIMAL(8,2) NOT NULL,
	units VARCHAR(6) NOT NULL
) ENGINE=MyISAM;
COMMIT;

CREATE TABLE tbl_food (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INTEGER(11) NOT NULL,
	brand VARCHAR(125) NOT NULL,
	description VARCHAR(125) NOT NULL,
	amount DECIMAL(8,2) NOT NULL,
	units VARCHAR(15) NOT NULL,
	calories INTEGER(11) NOT NULL,
	sodium DECIMAL(8,2) NOT NULL DEFAULT 0,
	totalfat DECIMAL(8,2) NOT NULL DEFAULT 0,
	potassium DECIMAL(8,2) NOT NULL DEFAULT 0,
	saturated DECIMAL(8,2) NOT NULL DEFAULT 0,
	carbs DECIMAL(8,2) NOT NULL DEFAULT 0,
	polyunsaturated DECIMAL(8,2) NOT NULL DEFAULT 0,
	fiber DECIMAL(8,2) NOT NULL DEFAULT 0,
	monounsaturated DECIMAL(8,2) NOT NULL DEFAULT 0,
	sugars DECIMAL(8,2) NOT NULL DEFAULT 0,
	trans DECIMAL(8,2) NOT NULL DEFAULT 0,
	protein DECIMAL(8,2) NOT NULL DEFAULT 0,
	cholesterol DECIMAL(8,2) NOT NULL DEFAULT 0,	
	vitamin_a DECIMAL(8,2) NOT NULL DEFAULT 0,
	calcium DECIMAL(8,2) NOT NULL DEFAULT 0,
	vitamin_c DECIMAL(8,2) NOT NULL DEFAULT 0,	
	iron DECIMAL(8,2) NOT NULL DEFAULT 0	
) ENGINE=MyISAM;
COMMIT;
