CREATE DATABASE trackma1_trackmacros;
COMMIT;

CREATE TABLE tbl_user (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	email_address VARCHAR(50) NOT NULL,
	activation_code VARCHAR(12) NULL,
	activated TINYINT(4) NOT NULL DEFAULT 0
) ENGINE=MyISAM;
COMMIT;

CREATE TABLE tbl_weight (
	id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	date DATE NOT NULL,
	weight DECIMAL(4,1) NOT NULL,
	units VARCHAR(6) NOT NULL
) ENGINE=MyISAM;
COMMIT;


CREATE TABLE tbl_food (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INTEGER(11) NOT NULL,
	brand VARCHAR(125) NOT NULL,
	description VARCHAR(125) NOT NULL,
	amount DECIMAL(8,2) NOT NULL,
	units VARCHAR(15) NOT NULL,
	calories INTEGER(11) NOT NULL,
	totalfat INTEGER(4) NOT NULL DEFAULT 0,
	saturated INTEGER(4) NOT NULL DEFAULT 0,
	Polyunsaturated INTEGER(4) NOT NULL DEFAULT 0,
	Monounsaturated INTEGER(4) NOT NULL DEFAULT 0,
	trans INTEGER(4) NOT NULL  DEFAULT 0,
	cholesterol INTEGER(6) NOT NULL  DEFAULT 0,
	sodium INTEGER(6) NOT NULL  DEFAULT 0,
	potassium INTEGER(6) NOT NULL  DEFAULT 0,
	carbs INTEGER(4) NOT NULL  DEFAULT 0,
	fiber INTEGER(4) NOT NULL  DEFAULT 0,
	sugars INTEGER(4) NOT NULL  DEFAULT 0,
	protein INTEGER(4) NOT NULL  DEFAULT 0,
	vitamin_a INTEGER(4) NOT NULL  DEFAULT 0,
	vitamin_c INTEGER(4) NOT NULL  DEFAULT 0,
	calcium INTEGER(4) NOT NULL  DEFAULT 0,
	iron INTEGER(4) NOT NULL  DEFAULT 0	
) ENGINE=MyISAM;
COMMIT;
